In [10]:
import tensorflow as tf

In [11]:
a=tf.range(15)

print(a)
# print(b)

tf.Tensor([ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14], shape=(15,), dtype=int32)


In [12]:
tf.reshape(a,[3,5])

<tf.Tensor: shape=(3, 5), dtype=int32, numpy=
array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])>

In [14]:
tf.reduce_min(a,axis=0)

<tf.Tensor: shape=(), dtype=int32, numpy=0>

In [19]:
x=tf.random.normal([3,5])
x

<tf.Tensor: shape=(3, 5), dtype=float32, numpy=
array([[-2.7028027 ,  0.2577022 , -0.6560168 , -1.0949385 , -1.0334673 ],
       [ 0.04549666, -1.5769209 ,  1.1962228 ,  1.2696732 ,  2.27175   ],
       [-0.16315113,  0.06600047, -0.05016552, -1.4575697 , -1.5012451 ]],
      dtype=float32)>

In [25]:
tf.reduce_max(x,axis=0)


<tf.Tensor: shape=(5,), dtype=float32, numpy=
array([0.04549666, 0.2577022 , 1.1962228 , 1.2696732 , 2.27175   ],
      dtype=float32)>