In [39]:
import tensorflow as tf

In [40]:
x=tf.random.normal([2,4])
y=tf.random.normal([4,3])
b=tf.random.normal([3])

In [41]:
x@y

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 0.54618216,  2.2053468 ,  1.188151  ],
       [-0.4202224 ,  7.0434103 ,  3.9579122 ]], dtype=float32)>

In [42]:
w=x@y+b
w

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[-1.7501402,  0.514819 ,  1.3389899],
       [-2.7165446,  5.3528824,  4.108751 ]], dtype=float32)>

In [43]:
a=tf.range(5)
print(a)
b=tf.constant(2)
b

tf.Tensor([0 1 2 3 4], shape=(5,), dtype=int32)


<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [44]:
a/b

<tf.Tensor: shape=(5,), dtype=float64, numpy=array([0. , 0.5, 1. , 1.5, 2. ])>

In [45]:
a//b

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([0, 0, 1, 1, 2])>

In [46]:
a%b

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([0, 1, 0, 1, 0])>

In [47]:
ne=tf.pow(a,b)
ne

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([ 0,  1,  4,  9, 16])>

In [48]:
ne=ne**2
ne

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([  0,   1,  16,  81, 256])>