In [68]:
import tensorflow as tf

In [69]:
out=tf.random.normal([100,10])
out

<tf.Tensor: shape=(100, 10), dtype=float32, numpy=
array([[-7.18922675e-01, -1.04355109e+00,  7.38571823e-01,
        -4.34297204e-01,  4.89134975e-02, -5.70959151e-01,
         1.29300117e-01,  2.82599658e-01, -5.48836231e-01,
         2.11279422e-01],
       [-3.22927535e-01,  5.78319579e-02, -3.39026362e-01,
         3.53318870e-01,  7.30942309e-01,  8.10109198e-01,
        -1.14279509e+00, -8.43055248e-02, -8.05933952e-01,
         4.55747694e-01],
       [-6.31718397e-01,  1.47641599e+00,  2.75567859e-01,
         4.76820439e-01, -7.39430189e-01,  3.03340197e-01,
        -6.80304706e-01,  1.53138280e+00,  1.75859892e+00,
         6.72636151e-01],
       [ 6.57847703e-01,  1.68616486e+00, -7.53813803e-01,
         4.25811857e-01,  1.16664767e+00, -7.30638742e-01,
         1.14114404e+00, -7.26288855e-01,  5.39693773e-01,
         2.64126629e-01],
       [ 2.45855495e-01,  1.29498017e+00, -1.11190009e+00,
        -2.93541461e-01,  1.91238773e+00,  3.63030374e-01,
         1.18745792

In [70]:
out = tf.nn.softmax(out, axis=1)
out

<tf.Tensor: shape=(100, 10), dtype=float32, numpy=
array([[0.05143991, 0.03718056, 0.2209439 , 0.06837723, 0.11085803,
        0.05964306, 0.12013752, 0.14004119, 0.06097724, 0.13040127],
       [0.06291995, 0.09207678, 0.06191512, 0.12373098, 0.18050042,
        0.19537094, 0.02771561, 0.07987679, 0.03881695, 0.13707641],
       [0.02356348, 0.19399504, 0.05838065, 0.07139567, 0.02115733,
        0.06002474, 0.02244599, 0.20495684, 0.25724155, 0.08683874],
       [0.098224  , 0.2746693 , 0.02394092, 0.07788356, 0.16337541,
        0.02450223, 0.1592614 , 0.02460905, 0.08727785, 0.06625624],
       [0.06352579, 0.18137573, 0.01634122, 0.03704187, 0.33629146,
        0.07142306, 0.16288565, 0.09127181, 0.01485116, 0.0249923 ],
       [0.01638698, 0.03630889, 0.10316747, 0.1564916 , 0.04708271,
        0.10629348, 0.23627529, 0.08270933, 0.13439983, 0.08088445],
       [0.05953748, 0.29337358, 0.13508543, 0.1386485 , 0.02416324,
        0.10630216, 0.05898478, 0.04862663, 0.03153046, 0.1

In [71]:
pred = tf.argmax(out, axis=1)
pred

<tf.Tensor: shape=(100,), dtype=int64, numpy=
array([2, 5, 8, 1, 4, 6, 1, 8, 4, 4, 8, 0, 8, 0, 3, 1, 8, 9, 8, 3, 3, 0,
       5, 8, 8, 0, 8, 9, 4, 9, 8, 9, 3, 8, 4, 2, 7, 5, 5, 2, 8, 9, 2, 4,
       1, 9, 8, 4, 1, 9, 4, 2, 8, 2, 4, 8, 3, 3, 0, 2, 8, 6, 5, 6, 5, 6,
       4, 5, 1, 0, 5, 1, 2, 0, 4, 8, 4, 6, 1, 3, 1, 8, 1, 6, 5, 1, 7, 1,
       1, 6, 3, 0, 2, 6, 2, 4, 2, 8, 5, 4], dtype=int64)>

In [72]:
y=tf.random.uniform([100],dtype=tf.int64,maxval=10)
y

<tf.Tensor: shape=(100,), dtype=int64, numpy=
array([1, 9, 5, 5, 5, 2, 8, 6, 5, 7, 8, 8, 3, 8, 7, 3, 4, 7, 8, 9, 3, 4,
       3, 1, 2, 2, 9, 6, 2, 1, 9, 7, 8, 7, 7, 7, 8, 2, 8, 7, 6, 1, 8, 4,
       0, 8, 5, 2, 4, 7, 2, 2, 7, 6, 9, 0, 6, 0, 9, 8, 5, 6, 9, 3, 3, 2,
       2, 1, 5, 4, 5, 1, 0, 7, 7, 7, 2, 8, 1, 4, 8, 2, 6, 1, 5, 8, 2, 5,
       5, 8, 4, 1, 2, 5, 6, 9, 3, 9, 8, 8], dtype=int64)>

In [73]:
res=tf.equal(pred,y)
res

<tf.Tensor: shape=(100,), dtype=bool, numpy=
array([False, False, False, False, False, False, False, False, False,
       False,  True, False, False, False, False, False, False, False,
        True, False,  True, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False,  True, False,
       False, False, False, False, False, False,  True, False, False,
       False, False, False, False, False, False, False,  True, False,
       False, False, False, False, False, False, False,  True,  True,
       False, False, False, False, False, False,  True, False, False,
       False, False, False,  True, False, False, False, False, False,
       False, False,  True, False, False, False, False, False, False,
       False])>

In [74]:
out = tf.cast(out, dtype=tf.float32)

In [75]:
correct = tf.reduce_sum(out)
correct

<tf.Tensor: shape=(), dtype=float32, numpy=100.0>

In [76]:
correct/100

<tf.Tensor: shape=(), dtype=float32, numpy=1.0>