In [1]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
from keras import layers
tf.__version__

'2.11.0'

In [2]:
a=1.2
aa=tf.constant(1.2)
type(a), type(aa), tf.is_tensor(aa)

(float, tensorflow.python.framework.ops.EagerTensor, True)

In [3]:
x=tf.constant([1, 2., 3.3])
x

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([1. , 2. , 3.3], dtype=float32)>

In [4]:
x.numpy()

array([1. , 2. , 3.3], dtype=float32)

In [5]:
a=tf.constant([1.2])
a, a.shape

(<tf.Tensor: shape=(1,), dtype=float32, numpy=array([1.2], dtype=float32)>,
 TensorShape([1]))

In [6]:
a=tf.constant([1, 2, 3.])
a, a.shape

(<tf.Tensor: shape=(3,), dtype=float32, numpy=array([1., 2., 3.], dtype=float32)>,
 TensorShape([3]))

In [7]:
a=tf.constant([[1,2],[3,4]])
a, a.shape

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4]])>,
 TensorShape([2, 2]))

In [8]:
a=tf.constant([[[1,2],[3,4]], [[5,6],[7,8]]])
a, a.shape

(<tf.Tensor: shape=(2, 2, 2), dtype=int32, numpy=
 array([[[1, 2],
         [3, 4]],
 
        [[5, 6],
         [7, 8]]])>,
 TensorShape([2, 2, 2]))

In [9]:
a=tf.constant('Hello, Deep learning')
a

<tf.Tensor: shape=(), dtype=string, numpy=b'Hello, Deep learning'>

In [10]:
tf.strings.lower(a)

<tf.Tensor: shape=(), dtype=string, numpy=b'hello, deep learning'>

In [11]:
a=tf.constant(True)
a

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [12]:
a=tf.constant([True, False])
a

<tf.Tensor: shape=(2,), dtype=bool, numpy=array([ True, False])>

In [13]:
a=tf.constant(True)
a is True

False

In [14]:
tf.constant(123456789, dtype=tf.int16)
tf.constant(123456789, dtype=tf.int32)

<tf.Tensor: shape=(), dtype=int32, numpy=123456789>

In [15]:
tf.constant(np.pi, dtype=tf.float32)

<tf.Tensor: shape=(), dtype=float32, numpy=3.1415927>

In [16]:
tf.constant(np.pi, dtype=tf.float64)

<tf.Tensor: shape=(), dtype=float64, numpy=3.141592653589793>

In [17]:
a=tf.constant(np.pi, dtype=tf.float16)
print('before:', a.dtype)
if a.dtype!=tf.float32:
    a=tf.cast(a, tf.float32)
print('after:', a.dtype)

before: <dtype: 'float16'>
after: <dtype: 'float32'>


In [18]:
a=tf.constant(123456789, dtype=tf.int32)
tf.cast(a, tf.int16)

<tf.Tensor: shape=(), dtype=int16, numpy=-13035>

In [19]:
a=tf.constant([True, False])
tf.cast(a, tf.int32)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 0])>

In [20]:
a=tf.constant([-1, 0, 1, 2])
tf.cast(a, tf.bool)

<tf.Tensor: shape=(4,), dtype=bool, numpy=array([ True, False,  True,  True])>

In [21]:
a=tf.constant([-1, 0, 1, 2])
aa=tf.Variable(a)
aa.name, aa.trainable

('Variable:0', True)

In [22]:
a=tf.Variable([[1,2],[3,4]])
a

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[1, 2],
       [3, 4]])>

In [23]:
# create tensor from python list
tf.convert_to_tensor([1, 2.])

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1., 2.], dtype=float32)>

In [24]:
# create a tensor from numpy array
tf.convert_to_tensor(np.array([[1,2.],[3,4]]))

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[1., 2.],
       [3., 4.]])>

In [25]:
tf.zeros([]), tf.ones([])

(<tf.Tensor: shape=(), dtype=float32, numpy=0.0>,
 <tf.Tensor: shape=(), dtype=float32, numpy=1.0>)

In [26]:
tf.zeros([1]), tf.ones([1])

(<tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.], dtype=float32)>,
 <tf.Tensor: shape=(1,), dtype=float32, numpy=array([1.], dtype=float32)>)

In [27]:
tf.zeros([2,2])

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.]], dtype=float32)>

In [28]:
tf.ones([3,2])

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.],
       [1., 1.]], dtype=float32)>

In [29]:
a=tf.ones([2,3])
tf.zeros_like(a)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [30]:
a=tf.zeros([3, 2])
tf.zeros_like(a)

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.],
       [0., 0.]], dtype=float32)>

In [31]:
tf.fill([], -1)

<tf.Tensor: shape=(), dtype=int32, numpy=-1>

In [32]:
tf.fill([1], -1)

<tf.Tensor: shape=(1,), dtype=int32, numpy=array([-1])>

In [33]:
tf.fill([2,2], 99)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[99, 99],
       [99, 99]])>

In [34]:
tf.random.normal([2,2])

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.37903568, -0.3799231 ],
       [ 1.1842351 ,  0.58148324]], dtype=float32)>

In [35]:
tf.random.normal([2,2], mean=1, stddev=2)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0.19122094, 2.2778583 ],
       [1.054595  , 1.374312  ]], dtype=float32)>

In [36]:
tf.random.uniform([2,2])

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0.65920186, 0.13093221],
       [0.3747363 , 0.47983778]], dtype=float32)>

In [37]:
tf.random.uniform([2,2], maxval=10)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[7.090358 , 1.286248 ],
       [8.290786 , 5.5581245]], dtype=float32)>

In [38]:
tf.random.uniform([2,2], maxval=100, dtype=tf.int32)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 4, 31],
       [41, 47]])>

In [39]:
tf.range(10)

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])>

In [40]:
tf.range(10, delta=2)

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([0, 2, 4, 6, 8])>

In [41]:
tf.range(1, 10, delta=2)

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([1, 3, 5, 7, 9])>