In [22]:
import tensorflow as tf

In [23]:
a = tf.constant([1,2,3,4,5,6])
a

<tf.Tensor: shape=(6,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6])>

In [24]:
b = tf.constant([7,8,1,6]) 
b

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([7, 8, 1, 6])>

In [25]:
b = tf.pad(b, [[0,2]])
b

<tf.Tensor: shape=(6,), dtype=int32, numpy=array([7, 8, 1, 6, 0, 0])>

In [29]:
x=tf.random.normal([4,32,32,3])
x

<tf.Tensor: shape=(4, 32, 32, 3), dtype=float32, numpy=
array([[[[-0.40542936,  0.47311473,  0.128257  ],
         [-0.9149696 , -0.43065816,  0.29325488],
         [ 0.16186674, -0.63927454, -0.06009176],
         ...,
         [ 1.504693  , -0.82872206,  0.19962583],
         [-0.1411698 ,  1.0358526 , -1.4457514 ],
         [ 0.09598698, -0.15590386,  0.2508132 ]],

        [[ 1.3050967 , -0.57854354, -0.35650635],
         [-0.00548805,  0.08031706, -2.7229307 ],
         [ 0.910392  , -2.6311927 , -0.36893347],
         ...,
         [-0.4603425 ,  1.4744693 , -1.0342032 ],
         [-1.3590113 , -0.79146093, -0.8441431 ],
         [-0.06732379,  0.4721585 , -0.51592785]],

        [[-1.2249429 , -0.9432344 , -0.7750777 ],
         [-0.49175715,  0.6649966 ,  0.52659166],
         [ 0.71612483, -0.54981613,  1.5700955 ],
         ...,
         [-0.35890433, -1.6633072 ,  0.5817398 ],
         [ 0.88450754, -1.6482612 ,  0.8456939 ],
         [-0.66843325,  0.3461418 , -0.66852415]

In [28]:
tf.tile(x,[2,3,3,1])

<tf.Tensor: shape=(8, 96, 96, 3), dtype=float32, numpy=
array([[[[-8.83276403e-01, -8.77740979e-02, -1.87686217e+00],
         [-4.01434273e-01,  3.91289175e-01, -8.94286454e-01],
         [ 2.43676066e-01, -1.04859436e+00, -6.46452978e-02],
         ...,
         [ 3.28842998e-01,  1.46658158e+00,  5.90417206e-01],
         [ 8.49981487e-01,  5.34181893e-01, -7.40240991e-01],
         [-2.32558116e-01,  2.77128280e-03, -2.67343283e-01]],

        [[-1.62036431e+00,  4.97284383e-01, -6.16848052e-01],
         [ 3.98707956e-01, -1.45709372e+00, -6.51437521e-01],
         [-1.85739562e-01, -6.08742654e-01,  1.38440752e+00],
         ...,
         [-5.43545306e-01, -2.22290054e-01,  7.09873796e-01],
         [ 1.01455718e-01, -9.74060535e-01, -1.12126446e+00],
         [-1.06073844e+00, -2.54162359e+00,  1.32870269e+00]],

        [[ 8.11681509e-01, -3.36386859e-01,  2.78025717e-01],
         [ 4.28565145e-01, -8.37474987e-02,  6.11572385e-01],
         [ 1.61775112e-01, -3.84159945e-02, 

In [30]:
x = tf.range(9)
x

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8])>

In [31]:
tf.maximum(x,2) 

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([2, 2, 2, 3, 4, 5, 6, 7, 8])>

In [32]:
tf.minimum(x,7)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 7])>