In [12]:
import tensorflow as tf

In [13]:
x = tf.random.normal([2,784])
x

<tf.Tensor: shape=(2, 784), dtype=float32, numpy=
array([[ 0.5215265 , -1.9604266 , -0.7623712 , ..., -0.71939707,
         1.2883942 , -0.9723802 ],
       [-0.29726577, -0.4366185 ,  0.18908358, ..., -1.0543019 ,
         1.0572544 ,  1.0273591 ]], dtype=float32)>

In [14]:
w1 = tf.Variable(tf.random.truncated_normal([784, 256],stddev=0.1))
w1

<tf.Variable 'Variable:0' shape=(784, 300) dtype=float32, numpy=
array([[ 0.13725856, -0.04653733, -0.02553349, ...,  0.09683289,
        -0.1020085 ,  0.05068262],
       [ 0.05190977,  0.08354877,  0.10782357, ..., -0.01236802,
         0.18421899, -0.084236  ],
       [-0.00403175, -0.01174863,  0.00795815, ...,  0.14351492,
         0.03614243, -0.01334924],
       ...,
       [-0.1922083 , -0.01820664, -0.15796916, ...,  0.03729482,
         0.1436742 ,  0.06987461],
       [-0.09304549,  0.12405498,  0.04349183, ...,  0.13284843,
        -0.0843494 , -0.09817583],
       [-0.19656272, -0.17807578, -0.00450751, ..., -0.12611865,
         0.00923108,  0.03635057]], dtype=float32)>

In [15]:
b1 = tf.Variable(tf.zeros([256]))