In [17]:
import tensorflow as tf

In [18]:
x=tf.range(96)
x

<tf.Tensor: shape=(96,), dtype=int32, numpy=
array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95])>

In [19]:
x=tf.reshape(x,[4,2,4,3])
x

<tf.Tensor: shape=(4, 2, 4, 3), dtype=int32, numpy=
array([[[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8],
         [ 9, 10, 11]],

        [[12, 13, 14],
         [15, 16, 17],
         [18, 19, 20],
         [21, 22, 23]]],


       [[[24, 25, 26],
         [27, 28, 29],
         [30, 31, 32],
         [33, 34, 35]],

        [[36, 37, 38],
         [39, 40, 41],
         [42, 43, 44],
         [45, 46, 47]]],


       [[[48, 49, 50],
         [51, 52, 53],
         [54, 55, 56],
         [57, 58, 59]],

        [[60, 61, 62],
         [63, 64, 65],
         [66, 67, 68],
         [69, 70, 71]]],


       [[[72, 73, 74],
         [75, 76, 77],
         [78, 79, 80],
         [81, 82, 83]],

        [[84, 85, 86],
         [87, 88, 89],
         [90, 91, 92],
         [93, 94, 95]]]])>

In [20]:
x.ndim

4

In [21]:
x.shape

TensorShape([4, 2, 4, 3])

In [22]:
y=tf.reshape(x,[2,-1])
y

<tf.Tensor: shape=(2, 48), dtype=int32, numpy=
array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63,
        64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79,
        80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95]])>

In [23]:
add=tf.random.uniform([28,28],maxval=10,dtype=tf.int32)
add

<tf.Tensor: shape=(28, 28), dtype=int32, numpy=
array([[2, 8, 5, 5, 4, 5, 0, 2, 0, 2, 5, 6, 5, 9, 5, 7, 2, 5, 3, 1, 2, 1,
        3, 9, 5, 1, 7, 6],
       [5, 3, 7, 0, 4, 8, 2, 6, 5, 5, 2, 1, 7, 8, 2, 5, 4, 5, 2, 5, 1, 0,
        3, 2, 0, 8, 9, 2],
       [2, 8, 3, 4, 8, 6, 5, 3, 6, 9, 4, 2, 0, 9, 9, 6, 4, 6, 8, 0, 4, 2,
        1, 9, 3, 8, 0, 3],
       [8, 3, 3, 9, 7, 7, 7, 9, 9, 6, 2, 1, 2, 9, 2, 2, 7, 3, 4, 4, 8, 7,
        2, 5, 7, 2, 9, 8],
       [2, 3, 1, 5, 9, 6, 9, 5, 3, 9, 5, 5, 8, 7, 9, 1, 4, 5, 5, 2, 4, 4,
        4, 7, 2, 2, 6, 0],
       [4, 9, 0, 1, 4, 9, 6, 8, 8, 5, 8, 5, 8, 0, 8, 3, 5, 8, 3, 7, 8, 3,
        9, 3, 1, 8, 5, 5],
       [6, 4, 2, 0, 8, 8, 3, 9, 5, 7, 4, 0, 5, 7, 0, 9, 1, 5, 8, 5, 9, 8,
        4, 0, 6, 1, 6, 4],
       [1, 5, 5, 6, 9, 6, 8, 9, 4, 8, 2, 8, 4, 8, 0, 3, 4, 1, 9, 1, 3, 3,
        7, 3, 1, 8, 9, 5],
       [6, 2, 5, 4, 6, 5, 3, 0, 2, 1, 6, 6, 3, 0, 7, 7, 6, 3, 6, 8, 2, 3,
        9, 6, 7, 0, 4, 7],
       [6, 2, 1, 1, 0, 8, 2, 8, 7, 2, 5, 2,

In [24]:
add=tf.expand_dims(add,axis=1)
add

<tf.Tensor: shape=(28, 1, 28), dtype=int32, numpy=
array([[[2, 8, 5, 5, 4, 5, 0, 2, 0, 2, 5, 6, 5, 9, 5, 7, 2, 5, 3, 1, 2,
         1, 3, 9, 5, 1, 7, 6]],

       [[5, 3, 7, 0, 4, 8, 2, 6, 5, 5, 2, 1, 7, 8, 2, 5, 4, 5, 2, 5, 1,
         0, 3, 2, 0, 8, 9, 2]],

       [[2, 8, 3, 4, 8, 6, 5, 3, 6, 9, 4, 2, 0, 9, 9, 6, 4, 6, 8, 0, 4,
         2, 1, 9, 3, 8, 0, 3]],

       [[8, 3, 3, 9, 7, 7, 7, 9, 9, 6, 2, 1, 2, 9, 2, 2, 7, 3, 4, 4, 8,
         7, 2, 5, 7, 2, 9, 8]],

       [[2, 3, 1, 5, 9, 6, 9, 5, 3, 9, 5, 5, 8, 7, 9, 1, 4, 5, 5, 2, 4,
         4, 4, 7, 2, 2, 6, 0]],

       [[4, 9, 0, 1, 4, 9, 6, 8, 8, 5, 8, 5, 8, 0, 8, 3, 5, 8, 3, 7, 8,
         3, 9, 3, 1, 8, 5, 5]],

       [[6, 4, 2, 0, 8, 8, 3, 9, 5, 7, 4, 0, 5, 7, 0, 9, 1, 5, 8, 5, 9,
         8, 4, 0, 6, 1, 6, 4]],

       [[1, 5, 5, 6, 9, 6, 8, 9, 4, 8, 2, 8, 4, 8, 0, 3, 4, 1, 9, 1, 3,
         3, 7, 3, 1, 8, 9, 5]],

       [[6, 2, 5, 4, 6, 5, 3, 0, 2, 1, 6, 6, 3, 0, 7, 7, 6, 3, 6, 8, 2,
         3, 9, 6, 7, 0, 4, 7]],

    

In [25]:
add=tf.squeeze(add,axis=1)
add

<tf.Tensor: shape=(28, 28), dtype=int32, numpy=
array([[2, 8, 5, 5, 4, 5, 0, 2, 0, 2, 5, 6, 5, 9, 5, 7, 2, 5, 3, 1, 2, 1,
        3, 9, 5, 1, 7, 6],
       [5, 3, 7, 0, 4, 8, 2, 6, 5, 5, 2, 1, 7, 8, 2, 5, 4, 5, 2, 5, 1, 0,
        3, 2, 0, 8, 9, 2],
       [2, 8, 3, 4, 8, 6, 5, 3, 6, 9, 4, 2, 0, 9, 9, 6, 4, 6, 8, 0, 4, 2,
        1, 9, 3, 8, 0, 3],
       [8, 3, 3, 9, 7, 7, 7, 9, 9, 6, 2, 1, 2, 9, 2, 2, 7, 3, 4, 4, 8, 7,
        2, 5, 7, 2, 9, 8],
       [2, 3, 1, 5, 9, 6, 9, 5, 3, 9, 5, 5, 8, 7, 9, 1, 4, 5, 5, 2, 4, 4,
        4, 7, 2, 2, 6, 0],
       [4, 9, 0, 1, 4, 9, 6, 8, 8, 5, 8, 5, 8, 0, 8, 3, 5, 8, 3, 7, 8, 3,
        9, 3, 1, 8, 5, 5],
       [6, 4, 2, 0, 8, 8, 3, 9, 5, 7, 4, 0, 5, 7, 0, 9, 1, 5, 8, 5, 9, 8,
        4, 0, 6, 1, 6, 4],
       [1, 5, 5, 6, 9, 6, 8, 9, 4, 8, 2, 8, 4, 8, 0, 3, 4, 1, 9, 1, 3, 3,
        7, 3, 1, 8, 9, 5],
       [6, 2, 5, 4, 6, 5, 3, 0, 2, 1, 6, 6, 3, 0, 7, 7, 6, 3, 6, 8, 2, 3,
        9, 6, 7, 0, 4, 7],
       [6, 2, 1, 1, 0, 8, 2, 8, 7, 2, 5, 2,